registry:
    restart: always
    image: registry:2
    ports:
      - 172.17.4.1:5005:5005
    environment:
        REGISTRY_HTTP_TLS_CERTIFICATE: certs/prvt_registry.cert
        REGISTRY_HTTP_TLS_KEY: certs/prvt_registry.key
        REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./data:/var/lib/registry
      - ./certs:/certs
