[package]
name = "t205"
version = "0.1.0"
authors = ["ckatsak <ckatsak@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
anyhow = "1.0"
#daemonize = "0.4"
log = "0.4"
log4rs = "0.13"
