---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: pynsider-sa
    labels:
        app: pyntainerdb
        tier: pynsider
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
    name: pynsider-role
    namespace: default
    labels:
        app: pyntainerdb
        tier: pynsider
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
        # - '*'
        # - VerbAll
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
    name: pynsider-rb
    namespace: default
    labels:
        app: pyntainerdb
        tier: pynsider
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: pynsider-role
    #kind: ClusterRole
    #name: view
subjects:
  - kind: ServiceAccount
    name: pynsider-sa
    namespace: default
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: pynsider
    namespace: default
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: pyntainerdb
                tier: pynsider
        spec:
            serviceAccountName: pynsider-sa
            containers:
              - name: pynsider
                image: ckatsak/pynsider:latest
                imagePullPolicy: Always
                stdin: true
                tty: true
                env:
                  - name: POD_NAME
                    valueFrom:
                        fieldRef:
                            fieldPath: metadata.name
                  - name: POD_NAMESPACE
                    valueFrom:
                        fieldRef:
                            fieldPath: metadata.namespace
                  - name: POD_IP
                    valueFrom:
                        fieldRef:
                            fieldPath: status.podIP
---
#apiVersion: v1
#kind: Pod
#metadata:
#    name: pynsider
#    namespace: default
#    labels:
#        app: pyntainerdb
#        tier: pynsider
#spec:
#    serviceAccountName: 'pynsider-sa'
#    containers:
#      - name: pynsider
#        image: ckatsak/pynsider:latest
#        imagePullPolicy: Always
#        stdin: true
#        tty: true
